version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - /home/outscale/db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
  mongo :
    image : mongo:4.2
    hostname : "mongo"
    restart : always
    environment :
      MONGO_INITDB_ROOT_USERNAME : mongodb
      MONGO_INITDB_ROOT_PASSWORD : mongodb
    labels :
      NAME : "mongo"
    ports :
      - 27017:27017
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/

  mongo-express :
    image : mongo-express:0.54
    hostname : "mongo-express"
    restart:  always
    depends_on:
      - "mongo"
    ports :
      - 8081:8081
    environment :
      ME_CONFIG_MONGODB_ADMINUSERNAME : mongodb
      ME_CONFIG_MONGODB_ADMINPASSWORD : mongodb
      ME_CONFIG_MONGODB_URL : mongodb://mongodb:mongodb@mongo:27017/
    labels :
      NAME : "mongo-express"

volumes:
  postgres:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/postgres'

  mongo:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/data/mongo'